### ISSUE TITLE
It would be helpful if cherry-picker would be compatible with pipx

### ISSUE THREAD

**Issue by cclauss** [python/cherry-picker#51]
% `pipx install cherry_picker`
```
  installed package cherry-picker 2.0.0, Python 3.9.7
  These apps are now globally available
    - cherry_picker
done! ✨ 🌟 ✨
```

% `cherry_picker 8e8f7522171ef82f2f5049940f815e00e38c6f42 3.9`
```
Traceback (most recent call last):
  File "/Users/user12345/.local/bin/cherry_picker", line 5, in <module>
    from cherry_picker import cherry_pick_cli
ImportError: cannot import name 'cherry_pick_cli' from 'cherry_picker'
```

**Comment by jaraco** [comment]
This is a duplicate of #26, which is fixed in main, but still broken when installed from pypi due to #48.

**Comment by jaraco** [comment]
You can work around the issue thus:

```
cpython main $ pipx install 'cherry_picker@git+https://github.com/python/cherry-picker'
  installed package cherry_picker 2.0.0, Python 3.10.0
  These apps are now globally available
    - cherry_picker
done! ✨ 🌟 ✨
cpython main $ cherry_picker
🐍 🍒 ⛏
Usage: cherry_picker [OPTIONS] [COMMIT_SHA1] [BRANCHES]...
Try 'cherry_picker -h' for help.

Error: At least one branch must be specified.
```
